// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwt_X085W4hZC8xkwiNVoZtlyT8aew0Tw',
    appId: '1:471695925917:web:7bd1246f9af1276160ea74',
    messagingSenderId: '471695925917',
    projectId: 'social-sphere-e7b56',
    authDomain: 'social-sphere-e7b56.firebaseapp.com',
    storageBucket: 'social-sphere-e7b56.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY6dmCRcyOFC2C1yrXCN19-99TPGPGZSU',
    appId: '1:471695925917:android:3a9120492ce5241460ea74',
    messagingSenderId: '471695925917',
    projectId: 'social-sphere-e7b56',
    storageBucket: 'social-sphere-e7b56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDs5FQS3P8M1vX0YNxUMVXwinfwunA0aM',
    appId: '1:471695925917:ios:8ed486bee68e3e3860ea74',
    messagingSenderId: '471695925917',
    projectId: 'social-sphere-e7b56',
    storageBucket: 'social-sphere-e7b56.firebasestorage.app',
    iosBundleId: 'com.example.socialSphere',
  );

}